### ISSUE TITLE
getLocation stopped working 2023-10-24

### ISSUE THREAD

**Issue by teleshoes** [w1ll1am23/pyeconet#35]
api call to /getLocation returns `{'results': {}, 'success': False, 'logs': 'The error has occurred in getLocation'}`

its been working perfectly for a few months for me, until yesterday. the awful app continues to work.

**Comment by teleshoes** [comment]
more specifically `{"error":{"id":"SOMEUUID","message":"Permission denied","detail":"Permission denied","line":"clearblade/core_code/module.go:184"},"statusCode":500}`

**Comment by w1ll1am23** [comment]
Report on HA's github

https://github.com/home-assistant/core/issues/102800

**Comment by teleshoes** [comment]
i do not use home assistant, though

**Comment by w1ll1am23** [comment]
@teleshoes can you confirm if the 0.1.21 release is working for you? Seems to be working for me locally but not working when I try to pull it in to Home Assistant. Another confirmation that its working outside of there would be helpful.

**Comment by teleshoes** [comment]
im sorry, its not working for me. same error
```
wolke:~/Code/pyeconet/src/pyeconet$ git rev-parse HEAD
c4243127e9cc919d3b6e57cd39648faebf84d6ed
wolke:~/Code/pyeconet/src/pyeconet$ md5sum api.py 
49efff02730996013c052c37ca247890  api.py
wolke:~/Code/pyeconet/src/pyeconet$ pyeconet 
Traceback (most recent call last):
  File "/home/wolke/bin/pyeconet", line 330, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/wolke/bin/pyeconet", line 84, in main
    all_equipment = await api.get_equipment_by_type(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wolke/.local/lib/python3.11/site-packages/pyeconet/api.py", line 173, in get_equipment_by_type
    await self._get_equipment()
  File "/home/wolke/.local/lib/python3.11/site-packages/pyeconet/api.py", line 138, in _get_equipment
    _locations: List = await self._get_location()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wolke/.local/lib/python3.11/site-packages/pyeconet/api.py", line 201, in _get_location
    raise GenericHTTPError(resp.status)
pyeconet.errors.GenericHTTPError: 401
wolke:~/Code/pyeconet/src/pyeconet$ md5sum /home/wolke/.local/lib/python3.11/site-packages/pyeconet/api.py
49efff02730996013c052c37ca247890  /home/wolke/.local/lib/python3.11/site-packages/pyeconet/api.py
```

**Comment by w1ll1am23** [comment]
Well okay... I must have done something wrong then. I'll take a closer look.

**Comment by teleshoes** [comment]
ok, problem solved! the new endpoint fixes it for me, you just typoed HEADERS for _headers, so the token header is missing from the POST

**Comment by w1ll1am23** [comment]
Ugh I've been looking that that for like 20 minutes lol I'll push up a fix
