### ISSUE TITLE
Bug when multiple PyEcoNet objects are instantiated

### ISSUE THREAD

**Issue by gnuite** [w1ll1am23/pyeconet#4]
First of all, thank you for this package.  I love it!

On [api.py:166](https://github.com/w1ll1am23/pyeconet/blob/master/src/pyeconet/api.py#L166), the HEADERS['Authorization'] template is populated with the token returned during authentication.  But it seems that this affects the HEADERS global, modifying the 'Authorization' value from 'Bearer %s' to 'Bearer [token]'.  Consider the following repro:

```
print(pyeconet.api.HEADERS)
PyEcoNet(ECONET_USERNAME, ECONET_PASSWORD)
print(pyeconet.api.HEADERS)
PyEcoNet(ECONET_USERNAME, ECONET_PASSWORD)
```

The first print shows: {'Authorization': 'Bearer %s', 'Content-Type': 'application/json'}
The second print shows: {'Authorization': 'Bearer abcdefg', 'Content-Type': 'application/json'}

And the second PyEcoNet invocation fails with:

```
Traceback (most recent call last):
  File "[redacted]/hpwh/main.py", line 21, in hpwh
    econet = PyEcoNet(ECONET_USERNAME, ECONET_PASSWORD)
  File "[redacted]/pyeconet/api.py", line 179, in __init__
    self.api_interface = EcoNetApiInterface(username, password)
  File "[redacted]/pyeconet/api.py", line 42, in __init__
    self.authenticated = self._authenticate()
  File "[redacted]/pyeconet/api.py", line 166, in _authenticate
    _auth = _auth % self.token
TypeError: not all arguments converted during string formatting
```

The hacky workaround is to re-set HEADERS['Authorization'] before instantiating PyEcoNet.

(In case it matters, this was repro'd in Python 3.7.5.)

**Comment by gnuite** [comment]
Note that the workaround can (theoretically, but probably not practically) break the first instance (if you're using them concurrently), so it's most valid if you don't plan on using the first instance anymore (which happens to be the case for me).  (One more parenthetical for good measure!)

**Comment by w1ll1am23** [comment]
This should no longer be an issue with the new API.
