### ISSUE TITLE
Can the delay to update state be decreased?

### ISSUE THREAD

**Issue by richardpowellus** [w1ll1am23/pyeconet#5]
I use Home Assistant which, in turn, uses pyeconet for its Econet integration. I noticed that every time I tried to change my hot water heater's mode (e.g. from "eco" to "high_demand") there would sometimes be a significant delay of minutes until the change would actually happen. This is counter to the official Android app which makes the change immediately.

I scrubbed through the code and noticed that there appears to be a 300 second minimum amount of time required to elapse before any communication goes back to Rheem which likely explains this behavior I'm seeing.

Can you explain why this significant delay was chosen? It also results in long waits between temperature updates (5 minutes I guess). I'm interested to know whether it could possible be made to be customizable to be a shorter span of time or if there were other reasons behind the decision. Thanks.

**Comment by w1ll1am23** [comment]
The new API is using push updates and should be merged to HA soon.
