### ISSUE TITLE
API Values Not Updating?

### ISSUE THREAD

**Issue by crossalchemist** [w1ll1am23/pyeconet#6]
I've been using this library for a few weeks to log data from some EcoNet water heaters. It was working great at first, but recently stopped providing updated data. All of the values in the json returned by get_locations have been the same for over a week.

Has the "unofficial API" stopped working? Strange that I still get a response though...

**Comment by crossalchemist** [comment]
Also unable to change setpoint. Receive error 503 when trying to change settings, no error when just requesting current state.

Below is an example test script where I check setpoint, change setpoint, and check that it changed:

```
HEADERS = {"Authorization": "Bearer %s", "Content-Type": "application/json"}
econet = PyEcoNet(email, password)
econet.api_interface.get_locations()
for location in econet.locations:
    _location_id = location.get("name")
    if _location_id == "3DDD":
        for device in location.get("equipment"):
            if device.get("type") == "Water Heater":
                print(_location_id + ": " + str(device.get("setPoint")))
                water_heater = econet.api_interface.get_device(device.get("id"))
                water_heater_modes = econet.api_interface.get_modes(device.get("id"))
                water_heater_usage = econet.api_interface.get_usage(device.get("id"))
                vacations = econet.api_interface.get_vacations()
                device_vacations = []
                for vacation in vacations:
                    for equipment in vacation.get("participatingEquipment"):
                        if equipment.get("id") == water_heater.get("id"):
                            device_vacations.append(EcoNetVacation(vacation, econet.api_interface))
                this_water_heater = EcoNetWaterHeater(water_heater, water_heater_modes, water_heater_usage,_location_id,device_vacations,econet.api_interface)
                this_water_heater.set_target_set_point(130)
                print(_location_id + ": " + str(device.get("setPoint")))
```

**Comment by richardpowellus** [comment]
I think Rheem/Econet has killed the API this library was relying on. I used to be able to login to the website to view my hot water heater and how it says it cannot connect to my equipment. However, the mobile app still works fine. I suspect they have a new API now that the mobile app is using and someone is going to have to try and reverse engineer that.

**Comment by analogue** [comment]
Looks like development for the new (MQTT based) undocumented API is in the works.  Join https://discord.gg/KQT2Xp6 for the latest developments.

**Comment by w1ll1am23** [comment]
The new API is fully working/merged now.
