### ISSUE TITLE
Old API no longer authenticating?

### ISSUE THREAD

**Issue by gnuite** [w1ll1am23/pyeconet#8]
As of July 23, 3:45 am PDT, PyEcoNet suddenly stopped being able to authenticate for me.  Each auth attempt results in:

`ERROR:pyeconet.api:Authentication request failed, please check credintials. 400`

I am still able to access the EcoNet app, although I understand it uses a different API.

Is anyone else having success authenticating?  Or is this the moment of "this library could stop working at any time, without warning"?  Or is it a matter of updating (or finding anew) the magic value for BASIC_HEADERS?

How's the new_api branch coming along? :)

**Comment by gnuite** [comment]
Looks like requests 2.24.0 might be the culprit.  I don't see this issue with requests 2.23.0.

**Comment by w1ll1am23** [comment]
The old API is no longer supported. New API is fully functional now.
